### PR TITLE
Link dlls

### PR DESCRIPTION
**Pull request by lawndoc**
I added the links for DLLs listed in each file doc.

I also added some commits to make testing Jekyll locally a better experience. I'll open a Wiki in this repo and add documentation for collaborators. I'll migrate #11 over to the Wiki as well.

### CODE REVIEW

**Comment by Mou-Ikkai** [comment]
Alright, seems good! Also, can I add the Adaptive CSS theme to Minima?

**Comment by lawndoc** [comment]
> Also, can I add the Adaptive CSS theme to Minima?

Sure we can check that out. Can you create a branch with it so I can see what it looks like before we merge it?

**Comment by Mou-Ikkai** [comment]
> > Also, can I add the Adaptive CSS theme to Minima?
> 
> Sure we can check that out. Can you create a branch with it so I can see what it looks like before we merge it?

I uh, already did it.

**Comment by Mou-Ikkai** [comment]
https://github.com/lawndoc/winbin.wtf/commit/10f3eacf08c6ba35075ad64938f3b9d82e1c856e

**Pull request merged**
